title: PLanCompS
description: >-
  PLanCompS: Programming Language Components and Specifications.
  Organization home page
repository: plancomps/plancomps.github.io
logo: /assets/images/PLanCompS-150.png
favicon_ico: /assets/images/favicon.ico
aux_links:
  PLanCompS on GitHub:
    - https://github.com/plancomps/plancomps.github.io
nav_external_links:
  - title: CBS-beta
    url: https://plancomps.github.io/CBS-beta
 
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-default-layout
  - rake

callouts:
  note:
    title: Note
    color: purple
