remote_theme: pmarsceill/just-the-docs
title: PLanCompS
description: Organization home page
repository: "plancomps/plancomps.github.io"
# Aux links for the upper right navigation
aux_links:
  "PLanCompS on GitHub":
    - "//github.com/plancomps/plancomps.github.io"
logo: "/assets/images/PLanCompS-150.png"
plugins:
    - jekyll-seo-tag
compress_html:
  blanklines: true
# Set the search token separator
search_tokenizer_separator: /[\s/]+/
